import "./admin-post-create/admin-post-create.component"
import "./admin-post-edit/admin-post-edit.component"
import "./admin-post-list/admin-post-list.component"
import "./admin-user/admin-user.component"
import "./post-list-tag/post-list-tag.component"
import "./post-list/post-list.component"
import "./post-view/post-view.component"